import {
  Activity,
  BookOpen,
  Bot,
  Braces,
  Brain,
  History,
  Files,
  Keyboard,
  LayoutDashboard,
  ListTodo,
  MessagesSquare,
  Mic2,
  MonitorDot,
  Puzzle,
  Radar,
  ShieldCheck,
  Settings,
  UsersRound,
  type LucideIcon,
} from 'lucide-react';
import type { RouteId } from '@/app/route-registry';

export const routeIcons: Record<RouteId, LucideIcon> = {
  overview: LayoutDashboard,
  input: Keyboard,
  agent: Bot,
  rooms: MessagesSquare,
  roles: UsersRound,
  plugins: Puzzle,
  browser: MonitorDot,
  voice: Mic2,
  planning: ListTodo,
  'work-documents': Files,
  memory: Brain,
  knowledge: BookOpen,
  governance: ShieldCheck,
  history: History,
  observability: Radar,
  'context-debug': Braces,
  diagnostics: Activity,
  configuration: Settings,
};
