import { ArrowUpRight, Download, FileSearch, ShieldCheck } from 'lucide-react';
import { useEffect, useState, type ReactNode } from 'react';
import { Button, Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/primitives';
import type { TraceDiagnosticReportV1 } from '@/contracts/generated/trace-diagnostic-report.v1';
import { buildTraceDiagnosticReportHtml } from './html-export';
import { buildTraceAuditReportModel, type TraceAuditEvidence, type TraceAuditFinding, type TraceAuditReportModel, type TraceAuditTimelineItem } from './report-model';

export function TraceDiagnosticReportDocument({ onOpenDiagnosticSession, onOpenTarget, onOpenTrace, report }: {
  onOpenDiagnosticSession: () => void;
  onOpenTarget: (target: TraceDiagnosticReportV1['targets'][number]) => void;
  onOpenTrace?: (traceId: string) => void;
  report: TraceDiagnosticReportV1;
}) {
  const model = buildTraceAuditReportModel(report);
  const exportHref = useTraceDiagnosticHtmlUrl(report);
  const [selectedEvidenceId, setSelectedEvidenceId] = useState('');
  const selectedEvidence = model.evidence.find((item) => item.evidenceId === selectedEvidenceId) ?? null;
  const selectedEvidenceTarget = report.targets.find((target) => target.targetKey === selectedEvidence?.targetKey) ?? null;
  const openEvidence = (evidenceId: string) => setSelectedEvidenceId(evidenceId);
  const usesSettlement = [model.plainConclusion, ...model.findings.map((item) => item.conclusion)].some((value) => value.toLowerCase().includes('settlement'));

  return <>
    <section aria-label="Trace 诊断网页报告" className="trace-audit" data-status={model.status} data-testid="trace-agent-web-report" data-tone={model.verdict.tone}>
      <header className="trace-audit__masthead">
        <div className="trace-audit__identity"><p className="trace-audit__document-type">PAW Trace Diagnostic · 工程审计报告</p><h2>{model.title}</h2><p className="trace-audit__lede">先看结论和影响，再看五层归因、事实与下一步；工程明细统一收在附录。</p></div>
        <dl className="trace-audit__document-meta"><Meta label="报告状态" value={model.statusLabel} /><Meta label="报告修订" value={`Revision ${model.revision}`} /><Meta label="更新时间" value={model.updatedAtLabel} /></dl>
      </header>

      <div className="trace-audit__scan-layer">
        <section aria-labelledby="trace-audit-tldr-title" className="trace-audit__tldr" data-tone={model.verdict.tone}>
          <div className="trace-audit__states" aria-label="事故、诊断与修复状态">{model.stateBadges.map((badge) => <div data-tone={badge.tone} key={badge.key}><span>{badge.label}</span><strong>{badge.value}</strong></div>)}</div>
          <div className="trace-audit__tldr-copy"><h3 id="trace-audit-tldr-title">{model.plainConclusion}</h3><p>{model.impact}</p><p className="trace-audit__glossary">{usesSettlement ? <span>settlement（会话结算）</span> : null}<span>回执（阶段完成凭证）</span><span>冻结（不可变快照）</span></p></div>
        </section>

        <ScanSection className="trace-audit__attribution" description={model.failureAttribution.summary} id="failure-attribution" title="问题出在哪一层">
          <ol className="trace-audit__attribution-list" data-primary-layer={model.failureAttribution.primaryLayer}>{model.failureAttribution.layers.map((item) => <li aria-label={`${item.label}：${item.verdictLabel}`} data-layer={item.layer} data-verdict={item.verdict} key={item.layer}><div className="trace-audit__attribution-label"><strong>{item.label}</strong><span>{item.verdictLabel}</span></div><p>{item.explanation}</p><EvidenceIds aliases={model.evidenceAliases} onOpen={openEvidence} values={item.evidenceIds} /></li>)}</ol>
        </ScanSection>

        <ScanSection className="trace-audit__knowledge" description="把已确认事实和仍缺少的证据放在一起，避免把未知写成结论。" id="knowledge" title="支持这个判断的事实">
          <div className="trace-audit__knowledge-columns"><section aria-labelledby="trace-audit-known-title"><h4 id="trace-audit-known-title">已知事实</h4><ul>{model.knownFacts.map((fact) => <li key={fact}>{fact}</li>)}</ul></section><section aria-labelledby="trace-audit-gaps-title"><h4 id="trace-audit-gaps-title">证据缺口</h4><ul>{model.evidenceGaps.map((gap) => <li key={gap}>{gap}</li>)}</ul></section></div>
        </ScanSection>

        <ScanSection className="trace-audit__actions-section" description="先确认修复授权，再读取修复 Trace 中已记录的修改与测试证据，由 AI Judge 复检；不声称在复检中重跑命令或进行同案 Trace 回放。" id="actions" title="下一步怎么做">
          <ol className="trace-audit__actions">{model.actions.map((action) => <li data-tone={action.tone} key={action.step}><span aria-hidden="true">{action.step}</span><div><strong>{action.title}</strong><p>{action.description}</p></div><small>{action.state}</small></li>)}</ol>
        </ScanSection>

        <ScanSection className="trace-audit__findings-section" description={model.summary} id="findings" title="进一步诊断依据">
          <div className="trace-audit__findings">{model.findings.length ? model.findings.map((finding) => <Finding aliases={model.evidenceAliases} finding={finding} key={finding.findingId} onOpenEvidence={openEvidence} />) : <p className="trace-audit__empty">没有结构化发现；这不等同于已经证明系统没有问题。</p>}</div>
        </ScanSection>

        <ScanSection className="trace-audit__cause-chain" description="只连接报告明确提供的因果关系；没有从错误字符串补写中间环节。" id="cause-chain" title="发生过程（证据链）">
          <ol className="trace-audit__cause-nodes">{model.causeChain.map((node, index) => <li data-state={node.state} key={`${node.evidenceId || 'gap'}:${index}`}><div className="trace-audit__cause-node"><span>{node.stateLabel}</span><strong>{node.label}</strong>{node.detail ? <p>{node.detail}</p> : null}{node.evidenceIds.length ? <EvidenceIds aliases={model.evidenceAliases} onOpen={openEvidence} values={node.evidenceIds} /> : null}</div>{index < model.causeChain.length - 1 ? <div aria-label={`${node.relationAfter || '关联'}，${node.relationConfidence || '置信度未知'}`} className="trace-audit__cause-connector"><span>{node.relationAfter || '关联待验证'}</span><small>{node.relationConfidence || '置信度未知'}</small></div> : null}</li>)}</ol>
        </ScanSection>
      </div>

      <details className="trace-audit__appendix"><summary><span><strong>技术附录</strong><small>扫描指标、时间线、环境、八维评分、Evidence、需求与修复对照</small></span><span className="trace-audit__details-affordance">展开明细</span></summary><div className="trace-audit__appendix-body">
        <AppendixSection id="verdict" title="原始审计判决"><div className="trace-audit__verdict"><strong>{model.verdict.title}</strong><p>{model.verdict.detail}</p>{model.failureReason ? <p><strong>报告失败原因：</strong>{model.failureReason}</p> : null}</div></AppendixSection>
        <AppendixSection id="scope" title="冻结诊断范围"><div className="trace-audit__targets">{model.targets.map((target) => <article data-source-available={target.sourceAvailable} key={target.targetKey}><div><strong>{target.title}</strong><span>{target.kindLabel} · {target.id}</span></div><span>{target.sourceAvailable ? '源快照可用' : '源快照不可用'}</span></article>)}</div></AppendixSection>
        <AppendixSection id="requirements" title="用户需求完成矩阵 · 需求矩阵">{model.requirements.length ? <div className="trace-audit__requirements">{model.requirements.map((requirement) => <article data-status={requirement.status} key={requirement.requirementId}><div><strong>{requirement.statement}</strong><span>{requirement.owner} · {requirement.authorityLabel}</span><p>{requirement.note}</p></div><span>{requirement.statusLabel}</span><EvidenceIds aliases={model.evidenceAliases} full onOpen={openEvidence} values={requirement.evidenceIds} /></article>)}</div> : <p className="trace-audit__empty">{model.requirementsSourceLabel}；不能从聚合数量倒推出逐条完成情况。</p>}</AppendixSection>
        {model.gates.length ? <AppendixSection id="gates" title="硬门槛"><div className="trace-audit__gates">{model.gates.map((gate) => <article data-status={gate.status} key={gate.gateId}><strong>{gate.gateId}</strong><span>{gate.statusLabel}</span><p>{gate.reason}</p><EvidenceIds aliases={model.evidenceAliases} full onOpen={openEvidence} values={gate.evidenceIds} /></article>)}</div></AppendixSection> : null}
        <AppendixSection id="metrics" title="扫描指标"><dl className="trace-audit__metrics">{model.metrics.map((metric) => <div data-available={metric.available} key={metric.key}><dt>{metric.label}</dt><dd>{metric.value}</dd><small>{metric.detail}</small></div>)}</dl></AppendixSection>
        <AppendixSection id="timeline" title="跨 Session / Agent 因果时间线 · 查看完整冻结时间线 · 完整时间线">{model.timeline.length ? <TimelineList aliases={model.evidenceAliases} items={model.timeline} onOpenEvidence={openEvidence} /> : <p className="trace-audit__empty">没有公开时间线。</p>}</AppendixSection>
        <AppendixSection id="environment" title="可复现环境快照 · 环境快照"><Environment model={model} /></AppendixSection>
        <AppendixSection id="dimensions" title={`八维诊断评分 · 八维评分明细（${model.dimensionSummary}）`}><DimensionTable aliases={model.evidenceAliases} model={model} onOpenEvidence={openEvidence} /></AppendixSection>
        <AppendixSection id="repair" title="修复授权状态"><RepairState model={model} /></AppendixSection>
        <AppendixSection id="comparison" title="修复前后 Trace / Eval 对照 · 修复对照"><Comparison model={model} onOpenTrace={onOpenTrace} /></AppendixSection>
        <AppendixSection id="evidence" title="Evidence 目录"><div className="trace-audit__evidence-catalog-list">{model.evidence.length ? model.evidence.map((item) => <button key={item.evidenceId} onClick={() => openEvidence(item.evidenceId)} type="button"><code>[{item.alias}] {item.evidenceId}</code><span>{item.summary}</span></button>) : <p className="trace-audit__empty">冻结报告不包含可公开展示的 Evidence。</p>}</div>{model.unresolvedEvidenceIds.length ? <p className="trace-audit__unresolved">{model.unresolvedEvidenceIds.length} 个引用未解析，未尝试从实时系统补齐。</p> : null}</AppendixSection>
      </div></details>

      <div aria-label="报告操作" className="trace-audit__links" role="toolbar">{exportHref ? <a className="trace-audit__download" download="trace-diagnostic-report.html" href={exportHref}><Download aria-hidden="true" size={16} />下载 HTML 报告</a> : <span aria-disabled="true" className="trace-audit__download">HTML 导出不可用</span>}<Button leadingIcon={<ShieldCheck size={16} />} onClick={onOpenDiagnosticSession} size="small">打开诊断 Agent 对话</Button>{report.targets.slice(0, 3).map((target) => <Button key={target.targetKey} leadingIcon={<ArrowUpRight size={16} />} onClick={() => onOpenTarget(target)} size="small" variant="quiet">打开{target.kind === 'room' ? ' Room' : target.kind === 'run' ? '运行记录' : ' Session'}</Button>)}</div>
      <footer className="trace-audit__provenance"><div><strong>报告身份</strong><span>{model.reportId}</span></div><div><strong>冻结检查摘要</strong><span>{model.inspectionSha256}</span></div><p>网页报告只读取持久化报告投影；诊断 Agent 对话保留过程，但不替代报告 authority。</p></footer>
    </section>

    <Dialog open={Boolean(selectedEvidenceId)} onOpenChange={(open) => { if (!open) setSelectedEvidenceId(''); }}><DialogContent className="trace-audit__evidence-dialog"><DialogHeader><DialogTitle>Evidence 详情</DialogTitle><DialogDescription>只读取报告冻结时保存的公开脱敏投影，不回查当前 Runtime。</DialogDescription></DialogHeader>{selectedEvidence ? <EvidenceDetail evidence={selectedEvidence} /> : <p className="trace-audit__evidence-missing" role="alert">未在冻结快照中找到 {selectedEvidenceId}，因此没有尝试读取未知原始数据。</p>}{selectedEvidence ? <div className="trace-audit__evidence-dialog-actions">{selectedEvidence.traceId && onOpenTrace ? <Button leadingIcon={<FileSearch size={16} />} onClick={() => onOpenTrace(selectedEvidence.traceId)} size="small">打开 Trace</Button> : null}{selectedEvidenceTarget ? <Button leadingIcon={<ArrowUpRight size={16} />} onClick={() => onOpenTarget(selectedEvidenceTarget)} size="small" variant="quiet">打开原对象</Button> : null}</div> : null}</DialogContent></Dialog>
  </>;
}

function ScanSection({ children, className, description, id, title }: { children: ReactNode; className: string; description: string; id: string; title: string }) { const headingId = `trace-audit-${id}-title`; return <section aria-labelledby={headingId} className={`trace-audit__section ${className}`}><header className="trace-audit__section-heading"><h3 id={headingId}>{title}</h3><p>{description}</p></header>{children}</section>; }
function AppendixSection({ children, id, title }: { children: ReactNode; id: string; title: string }) { const headingId = `trace-audit-appendix-${id}-title`; return <section aria-labelledby={headingId} className="trace-audit__appendix-section"><h3 id={headingId}>{title}</h3>{children}</section>; }

function EvidenceIds({ aliases, full = false, onOpen, values }: { aliases: Record<string, string>; full?: boolean; onOpen: (evidenceId: string) => void; values: string[] }) { return values.length ? <div className="trace-audit__evidence-ids">{values.map((value) => <button aria-label={`查看证据 ${value}`} key={value} onClick={() => onOpen(value)} type="button"><code>{full ? `[${aliases[value] ?? '?'}] ${value}` : `[${aliases[value] ?? '?'}]`}</code></button>)}</div> : <span className="trace-audit__evidence-empty">无冻结证据引用</span>; }

function Finding({ aliases, finding, onOpenEvidence }: { aliases: Record<string, string>; finding: TraceAuditFinding; onOpenEvidence: (evidenceId: string) => void }) { return <details className="trace-audit__finding" data-severity={finding.severity} open={['critical', 'high'].includes(finding.severity)}><summary><span className="trace-audit__finding-index">{finding.severityLabel}</span><span><strong>{finding.questionTitle}</strong><small>{finding.dimensionLabel}</small></span><span className="trace-audit__details-affordance">查看五段证据</span></summary><div className="trace-audit__finding-body"><FindingField title="事实" value={finding.observation} /><FindingField title="假设" value={finding.hypothesis} /><FindingField title="结论" value={finding.conclusion} /><FindingField title="候选修复" value={finding.candidateRepair} /><FindingField title="验证要求" value={finding.verification} /><section className="trace-audit__evidence"><h4>证据引用</h4><EvidenceIds aliases={aliases} onOpen={onOpenEvidence} values={finding.evidenceIds} /></section></div></details>; }
function FindingField({ title, value }: { title: string; value: string }) { return <section><h4>{title}</h4><p>{value}</p></section>; }
function TimelineList({ aliases, items, onOpenEvidence }: { aliases: Record<string, string>; items: TraceAuditTimelineItem[]; onOpenEvidence: (evidenceId: string) => void }) { return <ol className="trace-audit__timeline">{items.map((item) => <li key={`${item.evidenceId}:${item.sequence}`}><time>{item.createdAtLabel}</time><div><span>{item.targetLabel} · {item.kind}</span><strong>{item.summary}</strong></div><EvidenceIds aliases={aliases} full onOpen={onOpenEvidence} values={[item.evidenceId]} /></li>)}</ol>; }
function RepairState({ model }: { model: TraceAuditReportModel }) { const repair = model.repairLifecycle; return <article className="trace-audit__repair-state" data-state={repair.authorizationState}><div><span>修复交接</span><strong>{repair.authorizationStateLabel}</strong><p>{repair.writeAuthorityLabel}</p></div><dl><Meta label="Finding" value={repair.findingId || '尚未选择'} mono /><Meta label="来源对象" value={repair.sourceScope || '尚未冻结'} mono /><Meta label="失败引用" value={repair.failureRef || '尚未冻结'} mono /><Meta label="修复 Session" value={repair.repairSessionId || '尚未创建'} mono /><Meta label="授权回执" value={repair.authorizationId || '尚未记录'} mono /><Meta label="授权时间" value={repair.authorizedAtLabel} /></dl></article>; }

function Environment({ model }: { model: TraceAuditReportModel }) { return <><p className="trace-audit__appendix-status">{model.environment.statusLabel} · 捕获于 {model.environment.capturedAtLabel}</p>{model.environment.targets.length ? <div className="trace-audit__environment-targets">{model.environment.targets.map((target) => <article key={target.targetKey}><h4>{target.targetLabel}</h4><dl><Meta label="Runtime" value={target.runtime} /><Meta label="模型配置" value={target.modelProfile} /><Meta label="Tool 配置" value={target.toolProfileVersion} /><Meta label="执行模式" value={target.executionMode} /><Meta label="策略修订" value={target.policyRevision} /><Meta label="Shell 策略" value={target.shellPolicyVersion} /><Meta label="源快照 SHA-256" value={target.sourceSha256} mono /><Meta label="Workspace scope SHA-256" value={target.workspaceScopeSha256} mono /><Meta label="Trace input fingerprint" value={target.traceInputFingerprints.join(' · ') || '未冻结'} mono /><Meta label="Trace 状态" value={target.traceStatuses.join(' · ') || '未知'} /></dl></article>)}</div> : <p className="trace-audit__empty">没有 Runtime 权威环境数据，不能声称可复现。</p>}{model.environment.limitations.length ? <ul className="trace-audit__limitations">{model.environment.limitations.map((item) => <li key={item}>{item}</li>)}</ul> : null}</>; }
function DimensionTable({ aliases, model, onOpenEvidence }: { aliases: Record<string, string>; model: TraceAuditReportModel; onOpenEvidence: (evidenceId: string) => void }) { return <div className="trace-audit__score-table-wrap" data-testid="trace-diagnostic-scorecard"><table className="trace-audit__score-table"><thead><tr><th>维度与适用性</th><th>系统分数</th><th>AI 估计</th><th>指标与证据边界</th></tr></thead><tbody>{model.dimensions.map((dimension) => <tr data-applicability={dimension.applicability} data-dimension-id={dimension.dimensionId} key={dimension.dimensionId}><th scope="row"><strong>{dimension.title}</strong><span>{dimension.applicabilityLabel}</span></th><td><strong>{dimension.scoreText}</strong><span>{dimension.authorityLabel}</span></td><td><strong>{dimension.applicability === 'not_applicable' ? '不评分' : dimension.judgeScore === null ? '没有估计' : `${dimension.judgeScore}/3`}</strong>{dimension.judgeExplanation ? <span>{dimension.judgeExplanation}</span> : null}</td><td>{dimension.metrics.length ? dimension.metrics.map((metric) => <span key={`${dimension.dimensionId}:${metric.label}`}><strong>{metric.label}</strong> {metric.value}</span>) : <span>{dimension.note}</span>}<EvidenceIds aliases={aliases} full onOpen={onOpenEvidence} values={dimension.evidenceIds} /></td></tr>)}</tbody></table></div>; }
function Comparison({ model, onOpenTrace }: { model: TraceAuditReportModel; onOpenTrace?: (traceId: string) => void }) {
  const repair = model.repairLifecycle;
  const testAuthorityLabel = repair.sandboxStatus === 'not_required'
    ? '全信任 Session 终态测试证据'
    : 'Host 沙盒测试证据';
  const testAuthorityValue = repair.sandboxStatus === 'not_required'
    ? `${repair.testStatus} · 未在 Host 沙盒复跑`
    : `${repair.sandboxStatus} · ${repair.sandboxedTestCount} 次`;
  return <div className="trace-audit__comparison" data-status={repair.comparisonStatus}><header><div><span>验证状态</span><strong>{repair.verificationStateLabel}</strong></div><div><span>可比性</span><strong>{repair.comparisonStatusLabel}</strong></div><div><span>测试证据</span><strong>{repair.testStatus}</strong></div><div><span>{testAuthorityLabel}</span><strong>{testAuthorityValue}</strong></div></header><dl className="trace-audit__comparison-refs"><MetaAction label="诊断 Trace" onClick={repair.sourceTraceId && onOpenTrace ? () => onOpenTrace(repair.sourceTraceId) : undefined} value={repair.sourceTraceId || '未绑定'} /><MetaAction label="修复 Trace" onClick={repair.repairTraceId && onOpenTrace ? () => onOpenTrace(repair.repairTraceId) : undefined} value={repair.repairTraceId || '等待修复 Trace'} /><Meta label="AI Judge EvalRun" value={repair.evalRunId || '等待 AI Judge Eval'} mono /><Meta label="修复回执" value={repair.repairReceiptId || '尚未生成'} mono /></dl><p>{repair.comparisonReason}</p>{repair.comparisonMetrics.length ? <div className="trace-audit__comparison-table-wrap"><table><thead><tr><th>指标</th><th>Before</th><th>After</th><th>Δ</th></tr></thead><tbody>{repair.comparisonMetrics.map((metric) => <tr key={metric.metricId}><th scope="row">{metric.metricId}</th><td>{metric.before}</td><td>{metric.after}</td><td>{metric.delta}</td></tr>)}</tbody></table></div> : <p className="trace-audit__empty">还没有可展示的修复前后指标。</p>}</div>;
}

function EvidenceDetail({ evidence }: { evidence: TraceAuditEvidence }) { return <div className="trace-audit__evidence-detail"><p>{evidence.summary}</p><dl><Meta label="短引用" value={`[${evidence.alias}]`} mono /><Meta label="Evidence ID" value={evidence.evidenceId} mono /><Meta label="来源类型" value={evidence.sourceKind} /><Meta label="Source ref" value={evidence.sourceRef} mono /><Meta label="诊断对象" value={evidence.targetLabel} /><Meta label="Trace" value={evidence.traceId || '未绑定'} mono /><Meta label="状态" value={evidence.status} /><Meta label="时间" value={evidence.createdAtLabel} /></dl></div>; }
function Meta({ label, mono = false, value }: { label: string; mono?: boolean; value: string }) { return <div><dt>{label}</dt><dd data-mono={mono}>{value}</dd></div>; }
function MetaAction({ label, onClick, value }: { label: string; onClick?: () => void; value: string }) { return <div><dt>{label}</dt><dd data-mono="true">{onClick ? <button className="trace-audit__reference-link" onClick={onClick} type="button">{value}</button> : value}</dd></div>; }
function useTraceDiagnosticHtmlUrl(report: TraceDiagnosticReportV1): string { const [url, setUrl] = useState(''); useEffect(() => { if (typeof URL.createObjectURL !== 'function') return undefined; const next = URL.createObjectURL(new Blob([buildTraceDiagnosticReportHtml(report)], { type: 'text/html;charset=utf-8' })); setUrl(next); return () => URL.revokeObjectURL(next); }, [report]); return url; }
