"""Lab error contracts through the actual HTTP server and descriptor dispatcher."""

from __future__ import annotations

import json
import os
import sqlite3
import threading
import unittest
from dataclasses import replace
from http.server import ThreadingHTTPServer
from pathlib import Path
from types import SimpleNamespace
from urllib.error import HTTPError
from urllib.parse import urlencode
from urllib.request import Request, urlopen
from unittest.mock import Mock, patch

from rag_ime.agent_lab.golden import (
    AgentLabGoldenConflict,
    AgentLabGoldenValidationError,
)
from rag_ime.agent_lab.projects import AgentLabProjectConflict, AgentLabProjectNotFound
from rag_ime.agent_lab.scene_recipes import (
    AgentLabSceneRecipeConflict,
    AgentLabSceneRecipeUnavailable,
)
from rag_ime.agent_lab.trials import AgentLabTrialConflict, AgentLabTrialNotFound
from rag_ime.control_api.route_table import ROUTE_TABLE, find_route
from rag_ime.debug_server import DebugRequestHandler

BASE = "/api/agent/eval-lab/"
CASES = {
    "trials": ("eval_lab_trials", ("jobId",)),
    "golden": ("eval_lab_golden", ("suiteId",)),
    "projects": (
        "eval_lab_projects",
        ("projectId", "materialSetId", "artifactId", "artifactRevision"),
    ),
    "scene-recipes": ("eval_lab_scene_recipes", ("sceneId", "experimentId")),
}
# Exact existing responses; these are deliberately not generated by the adapters.
INVALID = {
    "trials": (
        422,
        {
            "ok": False,
            "code": "AGENT_LAB_TRIAL_INVALID_REQUEST",
            "error": "场景试验参数无效，请核对后重试。",
        },
    ),
    "golden": (
        422,
        {
            "ok": False,
            "code": "AGENT_LAB_GOLDEN_INVALID_REQUEST",
            "message": "评测操作参数无效，请核对后重试。",
        },
    ),
    "projects": (
        422,
        {
            "ok": False,
            "code": "AGENT_LAB_PROJECT_INVALID_REQUEST",
            "message": "项目操作参数无效，请核对后重试。",
        },
    ),
    "scene-recipes": (
        400,
        {
            "ok": False,
            "code": "AGENT_LAB_SCENE_RECIPE_INVALID_REQUEST",
            "error": "场景操作参数无效，请核对后重试。",
        },
    ),
}
INTERNAL = {
    "trials": (
        500,
        {
            "ok": False,
            "code": "AGENT_LAB_TRIAL_INTERNAL_ERROR",
            "error": "场景试验服务暂时不可用；已保存的执行记录仍会保留。",
        },
    ),
    "golden": (
        500,
        {
            "ok": False,
            "code": "AGENT_LAB_GOLDEN_INTERNAL_ERROR",
            "message": "评测服务暂时不可用；已保存的记录仍会保留。",
        },
    ),
    "projects": (
        500,
        {
            "ok": False,
            "code": "AGENT_LAB_PROJECT_INTERNAL_ERROR",
            "message": "项目服务暂时不可用；已保存的成果仍会保留。",
        },
    ),
    "scene-recipes": (
        500,
        {
            "ok": False,
            "code": "AGENT_LAB_SCENE_RECIPE_INTERNAL_ERROR",
            "error": "场景配置服务暂不可用，请刷新查看状态。",
        },
    ),
}
STORAGE = {
    "trials": (
        503,
        {
            "ok": False,
            "code": "AGENT_LAB_TRIAL_UNAVAILABLE",
            "error": "场景试验暂时无法读取或保存，请保留原请求后重试。",
        },
    ),
    "golden": (
        503,
        {
            "ok": False,
            "code": "AGENT_LAB_GOLDEN_UNAVAILABLE",
            "message": "评测集暂时无法读取或保存，请稍后重试。",
        },
    ),
    "projects": (
        503,
        {
            "ok": False,
            "code": "AGENT_LAB_PROJECT_UNAVAILABLE",
            "message": "优化项目暂时无法读取或保存，请稍后重试。",
        },
    ),
    "scene-recipes": (
        503,
        {
            "ok": False,
            "code": "AGENT_LAB_SCENE_RECIPE_SERVICE_UNAVAILABLE",
            "reasonCode": "storage_unavailable",
            "error": "场景配置服务暂不可用，请稍后重试。",
        },
    ),
}


class LabHttpErrorTests(unittest.TestCase):
    def setUp(self) -> None:
        self.readers = {
            key: Mock(return_value={"ok": True, "items": []}) for key in CASES
        }
        agent = SimpleNamespace(
            **{CASES[key][0]: reader for key, reader in self.readers.items()}
        )
        self.service = SimpleNamespace(
            agent=agent, config=SimpleNamespace(server_name="agent gateway")
        )

        class Handler(DebugRequestHandler):
            def log_message(self, _format, *args):
                pass

        Handler.service = self.service
        Handler.static_dir = Path("debug")
        self.server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self.thread = threading.Thread(target=self.server.serve_forever, daemon=True)
        self.thread.start()
        self.addCleanup(self.server.server_close)
        self.addCleanup(self.thread.join, 2)
        self.addCleanup(self.server.shutdown)

    def get(self, path, *, headers=None):
        request = Request(
            f"http://127.0.0.1:{self.server.server_port}{path}", headers=headers or {}
        )
        try:
            response = urlopen(request, timeout=5)
        except HTTPError as error:
            response = error
        with response:
            self.assertEqual(
                response.headers["Content-Type"], "application/json; charset=utf-8"
            )
            self.assertEqual(response.headers["Cache-Control"], "no-store")
            return response.status, json.loads(response.read())

    def test_success_defaults_and_query_selection(self):
        for key, (_handler, fields) in CASES.items():
            with self.subTest(route=key):
                self.assertEqual(self.get(BASE + key), (200, {"ok": True, "items": []}))
                self.readers[key].assert_called_once_with(dict.fromkeys(fields, ""))
                self.readers[key].reset_mock()
                query = [(field, f"中文-{index}") for index, field in enumerate(fields)]
                query += [(fields[0], "second-value"), ("ignored", "not-forwarded")]
                self.get(BASE + key + "?" + urlencode(query))
                self.readers[key].assert_called_once_with(
                    {field: f"中文-{index}" for index, field in enumerate(fields)}
                )
                descriptor = find_route("GET", BASE + key)
                self.assertFalse(descriptor.remote_safe)
                self.assertEqual(descriptor.aliases, ())
                self.assertEqual(descriptor.contract, "")
                self.assertEqual(descriptor.response_contract, "")

    def test_parameter_storage_and_internal_errors_keep_exact_responses(self):
        private = "/private/paw.sqlite token=do-not-publish"
        for key in CASES:
            failures = (
                (ValueError(private), INVALID[key]),
                (
                    TypeError(private),
                    INVALID[key] if key == "trials" else INTERNAL[key],
                ),
                (OSError(private), STORAGE[key]),
                (sqlite3.OperationalError(private), STORAGE[key]),
                (RuntimeError(private), INTERNAL[key]),
            )
            for failure, expected in failures:
                with self.subTest(route=key, failure=type(failure).__name__):
                    self.readers[key].side_effect = failure
                    self.assertEqual(self.get(BASE + key), expected)

    def test_business_errors_keep_status_and_receipt_fields(self):
        cases = [
            (
                "trials",
                AgentLabTrialNotFound(),
                (
                    404,
                    {
                        "ok": False,
                        "code": "AGENT_LAB_TRIAL_NOT_FOUND",
                        "error": "未找到这次场景试验。",
                    },
                ),
            ),
            (
                "trials",
                AgentLabTrialConflict(),
                (
                    409,
                    {
                        "ok": False,
                        "code": "AGENT_LAB_TRIAL_CONFLICT",
                        "reasonCode": "request_id_conflict",
                        "error": "The trial request ID is already bound to different input.",
                    },
                ),
            ),
            (
                "golden",
                AgentLabGoldenValidationError("invalid suite"),
                (
                    422,
                    {
                        "ok": False,
                        "code": "AGENT_LAB_GOLDEN_VALIDATION",
                        "message": "invalid suite",
                    },
                ),
            ),
            (
                "golden",
                AgentLabGoldenConflict("revision conflict"),
                (
                    409,
                    {
                        "ok": False,
                        "code": "AGENT_LAB_GOLDEN_CONFLICT",
                        "message": "revision conflict",
                    },
                ),
            ),
            (
                "projects",
                AgentLabProjectNotFound("missing project"),
                (
                    404,
                    {
                        "ok": False,
                        "code": "AGENT_LAB_PROJECT_NOT_FOUND",
                        "message": "missing project",
                    },
                ),
            ),
            (
                "projects",
                AgentLabProjectConflict("revision conflict"),
                (
                    409,
                    {
                        "ok": False,
                        "code": "AGENT_LAB_PROJECT_CONFLICT",
                        "message": "revision conflict",
                    },
                ),
            ),
            (
                "scene-recipes",
                AgentLabSceneRecipeUnavailable("missing", "missing recipe"),
                (
                    422,
                    {
                        "ok": False,
                        "code": "AGENT_LAB_SCENE_RECIPE_UNAVAILABLE",
                        "reasonCode": "missing",
                        "error": "missing recipe",
                    },
                ),
            ),
            (
                "scene-recipes",
                AgentLabSceneRecipeConflict(
                    "revision", "revision conflict", current_revision=7
                ),
                (
                    409,
                    {
                        "ok": False,
                        "code": "AGENT_LAB_SCENE_RECIPE_CONFLICT",
                        "reasonCode": "revision",
                        "error": "revision conflict",
                        "currentRevision": 7,
                    },
                ),
            ),
        ]
        for key, failure, expected in cases:
            with self.subTest(route=key, failure=type(failure).__name__):
                self.readers[key].side_effect = failure
                self.assertEqual(self.get(BASE + key), expected)

    def test_auth_and_remote_policy_run_before_lab_error_mapping(self):
        with patch.dict(
            os.environ, {"RAG_IME_REMOTE_ALLOWED_LOGINS": "reader@example.test"}
        ):
            for key in CASES:
                for headers, code in (
                    ({"Host": "paw.example.test"}, "scope_required"),
                    (
                        {
                            "Host": "paw.example.test",
                            "Tailscale-User-Login": "reader@example.test",
                        },
                        "route_not_allowed",
                    ),
                ):
                    with self.subTest(route=key, code=code):
                        status, body = self.get(BASE + key, headers=headers)
                        self.assertEqual(status, 403)
                        self.assertEqual(body["errorCode"], code)
                        self.assertEqual(
                            body["schemaVersion"], "rag-ime.gateway-access.v1"
                        )
                        self.readers[key].assert_not_called()

    def test_new_read_and_alias_use_declared_adapter_without_a_server_branch(self):
        original = find_route("GET", BASE + "trials")
        route = replace(
            original,
            path=BASE + "new-query",
            aliases=(BASE + "new-query-alias",),
            handler="agent.another_lab_read",
        )
        self.service.agent.another_lab_read = Mock(
            side_effect=ValueError("private detail")
        )
        entries = {("GET", path): route for path in (route.path, *route.aliases)}
        with patch.dict(ROUTE_TABLE, entries):
            for path in (route.path, *route.aliases):
                self.assertEqual(self.get(path), INVALID["trials"])

    def test_request_handler_response_validation_order_is_preserved(self):
        for key in CASES:
            original = find_route("GET", BASE + key)
            route = replace(
                original, contract="request.schema", response_contract="response.schema"
            )
            calls = []

            def validate(_payload, contract, recorded=calls):
                recorded.append(contract)

            def read(_payload, recorded=calls):
                recorded.append("handler")
                return {"ok": True}

            self.readers[key].side_effect = read
            with (
                self.subTest(route=key),
                patch.dict(ROUTE_TABLE, {("GET", route.path): route}),
                patch("rag_ime.control_api.dispatch.validate_contract", side_effect=validate),
            ):
                self.assertEqual(self.get(route.path), (200, {"ok": True}))
                self.assertEqual(
                    calls, ["request.schema", "handler", "response.schema"]
                )
            self.readers[key].reset_mock()
            with (
                patch.dict(ROUTE_TABLE, {("GET", route.path): route}),
                patch(
                    "rag_ime.control_api.dispatch.validate_contract",
                    side_effect=ValueError("bad request"),
                ),
            ):
                self.assertEqual(self.get(route.path), INVALID[key])
                self.readers[key].assert_not_called()
            response_only = replace(original, response_contract="response.schema")
            with (
                patch.dict(ROUTE_TABLE, {("GET", route.path): response_only}),
                patch(
                    "rag_ime.control_api.dispatch.validate_contract",
                    side_effect=ValueError("bad response"),
                ),
            ):
                self.assertEqual(self.get(route.path), INVALID[key])
                self.readers[key].assert_called_once()

    def test_error_boundary_includes_transform_and_response_encoding(self):
        for key in CASES:
            original = find_route("GET", BASE + key)
            transform = Mock(side_effect=ValueError("bad transform"))
            route = replace(original, transform=transform)
            with (
                self.subTest(route=key),
                patch.dict(ROUTE_TABLE, {("GET", route.path): route}),
            ):
                self.assertEqual(self.get(route.path), INVALID[key])
                self.readers[key].assert_not_called()
            self.readers[key].return_value = {"unserializable": object()}
            expected = INVALID[key] if key == "trials" else INTERNAL[key]
            self.assertEqual(self.get(original.path), expected)


if __name__ == "__main__":
    unittest.main()
