import { PREVIEW_REPORT_BYTES } from '@/features/agent/preview-data';
import type { RoomTaskSubagentRun } from '@/features/rooms/kernel/RoomTaskFlowGraph';

function roomPostBlock(
  id: string,
  type: string,
  presentationKind: string,
  summary: string,
  data: Record<string, unknown>,
): Record<string, unknown> {
  return {
    schemaVersion: 'rag-ime.agent-block.v1',
    id,
    type,
    status: 'completed',
    presentationKind,
    data,
    summary,
    source: {},
    visibility: 'room_post',
    digest: 'd'.repeat(64),
    ref: `ref:${id}`,
    generation: 0,
  };
}

export function previewRoomSnapshot(roomId: string) {
  const now = Date.now() - 60_000;
  const rootId = `${roomId}:turn-1`;
  const participants = [
    previewParticipant(roomId, 'participant-present', 'session-room-present', 'companion-present-v1', '澄·今', 0),
    previewParticipant(roomId, 'participant-firstlight', 'session-room-firstlight', 'companion-firstlight-v1', '澄·初', 1),
    previewParticipant(roomId, 'participant-future', 'session-room-future', 'companion-future-v1', '澄·远', 2),
  ];
  const event = (
    sequence: number,
    eventType: string,
    participantId: string | null,
    payload: Record<string, unknown>,
  ) => ({
    schemaVersion: 'rag-ime.agent-room-event.v1',
    eventId: `${roomId}:${sequence}`,
    roomId,
    sequence,
    turnId: rootId,
    eventType,
    participantId,
    sourceSessionId: participantId === 'participant-present'
      ? 'session-room-present'
      : participantId === 'participant-firstlight'
        ? 'session-room-firstlight'
        : participantId === 'participant-future'
          ? 'session-room-future'
          : '',
    createdAtMs: now + sequence,
    payload,
    resumeToken: `${roomId}:${sequence}`,
  });
  const roomPost = (
    postId: string,
    participantId: string,
    dispatchId: string,
    content: string,
    createdAtMs: number,
    blocks?: Record<string, unknown>[],
  ) => ({
    schemaVersion: 'wisdom-weasel.room-post.v2',
    postId,
    roomId,
    rootId,
    generation: 0,
    dispatchId,
    authorActorRef: participantId,
    kind: 'result',
    visibility: 'room',
    content,
    idempotencyKey: postId,
    publicationSource: { kind: 'room_commit', ref: `commit:${postId}` },
    createdAtMs,
    ...(blocks ? { blocks } : {}),
  });
  const events = [
    event(1, 'user_message', null, {
      messageId: 'room-user-1', rootId,
      text: '并行实现 Room 任务图与依赖数据，整合后交给独立伙伴复核。',
    }),
    event(2, 'route_decision', 'participant-present', {
      rootId, dispatchId: 'dispatch-present',
      targetParticipantId: 'participant-present', targetDisplayName: '澄·今',
      reason: '负责任务图交互', summary: '澄·今已接手任务图交互',
    }),
    event(3, 'route_decision', 'participant-firstlight', {
      rootId, dispatchId: 'dispatch-firstlight',
      targetParticipantId: 'participant-firstlight', targetDisplayName: '澄·初',
      reason: '负责依赖数据', summary: '澄·初已接手依赖数据',
    }),
    event(4, 'participant_activity', 'participant-present', {
      rootId, dispatchId: 'dispatch-present', sourceEventId: 'tool-present-start',
      sourceEventType: 'tool_started', toolCallId: 'tool-present', toolName: 'read_file',
      summary: '读取 Room 时间线实现',
    }),
    event(5, 'participant_activity', 'participant-present', {
      rootId, dispatchId: 'dispatch-present', sourceEventId: 'tool-present-finish',
      sourceEventType: 'tool_finished', toolCallId: 'tool-present', toolName: 'read_file',
      summary: '已核对流式投影与 Post 替换', isError: false,
    }),
    event(6, 'participant_delta', 'participant-present', {
      rootId, dispatchId: 'dispatch-present', messageId: 'room-assistant-1',
      delta: '我会把工具进展留在当前消息里；完成后，这里会直接变成清晰的公开结果。',
    }),
    event(7, 'room_post', 'participant-present', {
      rootId, dispatchId: 'dispatch-present',
      post: roomPost(
        'room-post-present', 'participant-present', 'dispatch-present',
        '我已把实时进展收拢在同一条消息里；完成后会在原处留下清晰结果。',
        now + 7,
        /* The same managed report a Session turn delivers. Room routes results
           through the identical AgentBlocks renderer, so this is what proves
           the two workspaces share one result language rather than merely
           looking alike. Room post blocks carry the full agent-block.v1 shape
           — summary/source/visibility/digest/ref/generation are all required,
           and a post whose blocks fail validation is dropped whole. */
        [
          roomPostBlock('room-post-text', 'text', 'markdown', '结果说明', {
            text: '我已把实时进展收拢在同一条消息里；完成后会在原处留下清晰结果。',
          }),
          roomPostBlock('room-post-report', 'file', 'file', '词库健康报告', {
            mediaId: 'media_previewreport01',
            name: 'lexicon-health-report.html',
            mimeType: 'text/html',
            byteSize: PREVIEW_REPORT_BYTES,
            sha256: 'c'.repeat(64),
          }),
        ],
      ),
    }),
    event(8, 'participant_activity', 'participant-present', {
      rootId,
      dispatchId: 'dispatch-present',
      responsePostId: 'room-post-present',
      sourceEventId: 'message-present-completed',
      sourceEventType: 'message_completed',
      runtimeTurnId: 'runtime-turn-present',
      status: 'draft_ready',
      summary: '正在整理正式 Post',
      provider: 'openai',
      model: 'gpt-5.4',
      usageReported: true,
      cacheUsageReported: true,
      usage: { input: 12_480, output: 642, cacheRead: 9_600, cacheWrite: 0, totalTokens: 22_722 },
    }),
    event(9, 'turn_completed', 'participant-present', {
      rootId, dispatchId: 'dispatch-present', summary: '前端时间线检查完成',
    }),
    event(10, 'participant_activity', 'participant-firstlight', {
      rootId, dispatchId: 'dispatch-firstlight', sourceEventId: 'tool-firstlight-start',
      sourceEventType: 'tool_started', toolCallId: 'tool-firstlight', toolName: 'control_api',
      summary: '检查路由与权限回执',
    }),
    event(11, 'participant_delta', 'participant-firstlight', {
      rootId, dispatchId: 'dispatch-firstlight', messageId: 'room-assistant-2',
      delta: 'Control API 只在服务端确认后更新权限状态，失败回执不会伪装成已生效。',
    }),
    event(12, 'participant_activity', 'participant-firstlight', {
      rootId, dispatchId: 'dispatch-firstlight', sourceEventId: 'tool-firstlight-finish',
      sourceEventType: 'tool_finished', toolCallId: 'tool-firstlight', toolName: 'control_api',
      summary: '路由与权限回执检查完成', isError: false,
    }),
    event(13, 'room_post', 'participant-firstlight', {
      rootId, dispatchId: 'dispatch-firstlight',
      post: roomPost(
        'room-post-firstlight', 'participant-firstlight', 'dispatch-firstlight',
        '我核对了工作目录和授权边界：需要确认的操作会等你，公开消息也不会重复出现。',
        now + 13,
      ),
    }),
    event(14, 'participant_activity', 'participant-firstlight', {
      rootId,
      dispatchId: 'dispatch-firstlight',
      responsePostId: 'room-post-firstlight',
      sourceEventId: 'message-firstlight-completed',
      sourceEventType: 'message_completed',
      runtimeTurnId: 'runtime-turn-firstlight',
      status: 'draft_ready',
      summary: '正在整理正式 Post',
      provider: 'anthropic',
      model: 'claude-sonnet-4-5',
      usageReported: true,
      cacheUsageReported: true,
      usage: { input: 8_320, output: 418, cacheRead: 6_400, cacheWrite: 320, totalTokens: 15_458 },
    }),
    event(15, 'turn_completed', 'participant-firstlight', {
      rootId, dispatchId: 'dispatch-firstlight', summary: '依赖数据检查完成',
    }),
    event(16, 'turn_completed', null, { rootId, summary: '协作检查完成' }),
  ];
  return {
    schemaVersion: 'rag-ime.agent-room-snapshot.v1',
    ok: true,
    room: {
      schemaVersion: 'rag-ime.agent-room.v1',
      id: roomId,
      title: '迁移作战室',
      status: 'active',
      executionMode: 'workspace_managed',
      roomKind: 'collaboration',
      avatar: 'briefcase',
      description: '验证并行实现、整合依赖与独立复核',
      routingPolicy: 'natural',
      moderatorParticipantId: 'participant-present',
      activeTopicId: 'topic-preview',
      workspaceRoots: ['/Volumes/work/wisdom-weasel-rag-ime'],
      topics: [{
        schemaVersion: 'rag-ime.agent-room-topic.v1',
        id: 'topic-preview',
        roomId,
        title: '任务图依赖验证',
        summary: '两个实现分支并行推进，整合完成后交给独立伙伴复核。',
        status: 'active',
        ordinal: 0,
        createdAtMs: now,
        updatedAtMs: now,
      }],
      artifacts: [],
      workItems: [{
        schemaVersion: 'rag-ime.agent-room-work-item.v1',
        id: 'room-work:preview',
        roomId,
        topicId: 'topic-preview',
        rootTurnId: `${roomId}:turn-1`,
        rootWorkId: 'room-work:preview',
        parentWorkId: '',
        objective: '并行实现 Room 任务图，整合后交给独立伙伴复核',
        expectedOutput: '可复查的依赖图与独立复核结论',
        acceptanceCriteria: ['两项实现任务可并行推进', '整合依赖两个实现结果', '独立伙伴复核整合版本'],
        accountableParticipantId: 'participant-present',
        currentOwnerParticipantId: 'participant-future',
        offeredToParticipantId: '',
        createdByParticipantId: 'participant-present',
        clientMessageId: 'preview-assignment',
        state: 'review',
        depth: 1,
        revision: 1,
        resultSummary: '两个实现分支已完成，整合版本正在等待独立复核。',
        artifactRefs: [],
        evidenceRefs: ['test:room-graph-ui', 'test:room-graph-data'],
        blocker: {},
        acceptedTurnId: 'turn:preview-worker',
        createdAtMs: now + 2,
        updatedAtMs: now + 7,
        completedAtMs: null,
      }],
      createdAtMs: now,
      updatedAtMs: now + events.length,
      lastEventSequence: events.length,
      participants,
    },
    events,
    firstSequence: 1,
    lastSequence: events.length,
    resumeToken: `${roomId}:${events.length}`,
    truncated: false,
  };
}

export function previewRoomKernelSnapshot(roomId: string): Record<string, unknown> {
  const now = Date.now() - 24_000;
  const rootId = `${roomId}:root-preview`;
  const originalText = '并行实现 Room 任务图，整合后交给独立伙伴复核';
  const anchorId = `${rootId}:anchor`;
  const catalogRevisionId = `${rootId}:requirements-v1`;
  return {
    roomId,
    lastSequence: 1,
    snapshotHash: `sha256:${'b'.repeat(64)}`,
    roots: [{
      schemaVersion: 'wisdom-weasel.room-root-execution.v3',
      rootId,
      roomId,
      generation: 1,
      state: 'running',
      facilitatorParticipantId: 'participant-present',
      reporterParticipantId: null,
      reporterSelectionReceiptId: null,
      requirementAnchorRef: anchorId,
      createdByActorRef: 'user:preview',
      terminalReceiptId: null,
      activeProfileRef: null,
      budgetPolicyRef: 'budget:preview',
      independentReviewRequired: false,
      createdAtMs: now,
    }],
    tasks: [{
      schemaVersion: 'wisdom-weasel.room-task.v3',
      taskId: `${rootId}:task-interface`,
      rootId,
      parentTaskId: null,
      taskKind: 'work',
      currentOwnerParticipantId: 'participant-present',
      ownershipRevision: 0,
      ownershipReceiptId: null,
      objective: '实现 Room 任务图交互',
      expectedOutput: '可访问的任务图界面',
      requirementItemIds: [`${catalogRevisionId}:item:1`],
      acceptanceCriterionIds: [`${catalogRevisionId}:criterion:1`],
      contextEvidenceRefs: [`${rootId}:evidence-interface`],
      invitationId: null,
      reviewOfTaskIds: [],
      reviewAuthorParticipantIds: [],
      reviewState: 'not_required',
      revision: 1,
      state: 'completed',
    }, {
      schemaVersion: 'wisdom-weasel.room-task.v3',
      taskId: `${rootId}:task-data`,
      rootId,
      parentTaskId: null,
      taskKind: 'work',
      currentOwnerParticipantId: 'participant-firstlight',
      ownershipRevision: 0,
      ownershipReceiptId: null,
      objective: '接通 Room 依赖数据',
      expectedOutput: '稳定的依赖投影',
      requirementItemIds: [`${catalogRevisionId}:item:1`],
      acceptanceCriterionIds: [`${catalogRevisionId}:criterion:1`],
      contextEvidenceRefs: [`${rootId}:evidence-data`],
      invitationId: null,
      reviewOfTaskIds: [],
      reviewAuthorParticipantIds: [],
      reviewState: 'not_required',
      revision: 1,
      state: 'completed',
    }, {
      schemaVersion: 'wisdom-weasel.room-task.v3',
      taskId: `${rootId}:task-integration`,
      rootId,
      parentTaskId: null,
      taskKind: 'work',
      currentOwnerParticipantId: 'participant-present',
      ownershipRevision: 0,
      ownershipReceiptId: null,
      objective: '整合任务图与依赖数据',
      expectedOutput: '可供复核的整合版本',
      requirementItemIds: [`${catalogRevisionId}:item:1`],
      acceptanceCriterionIds: [`${catalogRevisionId}:criterion:1`],
      contextEvidenceRefs: [],
      invitationId: null,
      reviewOfTaskIds: [],
      reviewAuthorParticipantIds: ['participant-future'],
      reviewState: 'required',
      revision: 1,
      state: 'active',
    }, {
      schemaVersion: 'wisdom-weasel.room-task.v3',
      taskId: `${rootId}:task-review`,
      rootId,
      parentTaskId: `${rootId}:task-integration`,
      taskKind: 'review',
      currentOwnerParticipantId: 'participant-future',
      ownershipRevision: 1,
      ownershipReceiptId: `${rootId}:receipt-owner-review`,
      objective: '独立复核整合版本',
      expectedOutput: '独立复核结论',
      requirementItemIds: [`${catalogRevisionId}:item:1`],
      acceptanceCriterionIds: [`${catalogRevisionId}:criterion:1`],
      contextEvidenceRefs: [],
      invitationId: null,
      reviewOfTaskIds: [`${rootId}:task-integration`],
      reviewAuthorParticipantIds: ['participant-future'],
      reviewState: 'required',
      reviewTargetRevision: `sha256:${'e'.repeat(64)}`,
      reviewEvidenceNotBeforeMs: now + 13_000,
      reviewRound: 1,
      revision: 1,
      state: 'waiting',
    }],
    dispatches: [{
      schemaVersion: 'wisdom-weasel.room-dispatch-envelope.v2',
      dispatchId: `${rootId}:dispatch-interface`,
      rootId,
      taskId: `${rootId}:task-interface`,
      parentDispatchId: null,
      generation: 1,
      hopCount: 1,
      depth: 1,
      budgetCost: 1,
      targetSessionId: 'session-room-present',
      targetParticipantId: 'participant-present',
      triggerId: `${rootId}:trigger-interface`,
      intentKind: 'execute',
      idempotencyKey: `${rootId}:dispatch-interface`,
      attempt: 0,
      capabilityEpoch: 1,
      runtimeProfileRevision: 'preview-v1',
      alignmentOrdinal: 1,
      dependsOnDispatchIds: [],
      attachmentIds: [],
      state: 'committed',
    }, {
      schemaVersion: 'wisdom-weasel.room-dispatch-envelope.v2',
      dispatchId: `${rootId}:dispatch-data`,
      rootId,
      taskId: `${rootId}:task-data`,
      parentDispatchId: null,
      generation: 1,
      hopCount: 1,
      depth: 1,
      budgetCost: 1,
      targetSessionId: 'session-room-firstlight',
      targetParticipantId: 'participant-firstlight',
      triggerId: `${rootId}:trigger-data`,
      intentKind: 'execute',
      idempotencyKey: `${rootId}:dispatch-data`,
      attempt: 0,
      capabilityEpoch: 1,
      runtimeProfileRevision: 'preview-v1',
      alignmentOrdinal: 1,
      dependsOnDispatchIds: [],
      attachmentIds: [],
      state: 'committed',
    }, {
      schemaVersion: 'wisdom-weasel.room-dispatch-envelope.v2',
      dispatchId: `${rootId}:dispatch-integration`,
      rootId,
      taskId: `${rootId}:task-integration`,
      parentDispatchId: null,
      generation: 1,
      hopCount: 2,
      depth: 2,
      budgetCost: 1,
      targetSessionId: 'session-room-present',
      targetParticipantId: 'participant-present',
      triggerId: `${rootId}:trigger-integration`,
      intentKind: 'execute',
      idempotencyKey: `${rootId}:dispatch-integration`,
      attempt: 0,
      capabilityEpoch: 1,
      runtimeProfileRevision: 'preview-v1',
      alignmentOrdinal: 2,
      dependsOnDispatchIds: [
        `${rootId}:dispatch-interface`,
        `${rootId}:dispatch-data`,
      ],
      attachmentIds: [],
      state: 'running',
    }, {
      schemaVersion: 'wisdom-weasel.room-dispatch-envelope.v2',
      dispatchId: `${rootId}:dispatch-review`,
      rootId,
      taskId: `${rootId}:task-review`,
      parentDispatchId: `${rootId}:dispatch-integration`,
      generation: 1,
      hopCount: 3,
      depth: 3,
      budgetCost: 1,
      targetSessionId: 'session-room-future',
      targetParticipantId: 'participant-future',
      triggerId: `${rootId}:trigger-review`,
      intentKind: 'review',
      idempotencyKey: `${rootId}:dispatch-review`,
      attempt: 0,
      capabilityEpoch: 1,
      runtimeProfileRevision: 'preview-v1',
      alignmentOrdinal: 3,
      dependsOnDispatchIds: [`${rootId}:dispatch-integration`],
      attachmentIds: [],
      state: 'pending',
    }],
    posts: [{
      schemaVersion: 'wisdom-weasel.room-post.v2',
      postId: `${rootId}:post-progress`,
      roomId,
      rootId,
      generation: 1,
      authorActorRef: 'participant-present',
      kind: 'finding',
      visibility: 'room',
      content: '两个实现分支已经回传，正在整合任务图与依赖数据。',
      idempotencyKey: `${rootId}:post-progress`,
      publicationSource: { kind: 'room_commit', ref: 'commit:preview-progress' },
      createdAtMs: now + 10_000,
    }],
    sessions: [{
      sessionId: 'session-room-present',
      rootId,
      generation: 1,
      state: 'running',
      updatedAtMs: now + 20_000,
    }, {
      sessionId: 'session-room-firstlight',
      rootId,
      generation: 1,
      state: 'completed',
      updatedAtMs: now + 18_000,
    }, {
      sessionId: 'session-room-future',
      rootId,
      generation: 1,
      state: 'queued',
      updatedAtMs: now + 16_000,
    }],
    receipts: [{
      schemaVersion: 'wisdom-weasel.room-kernel-receipt.v1',
      receiptId: `${rootId}:receipt-owner-review`,
      rootId,
      commandId: null,
      receiptKind: 'accepted',
      status: 'applied',
      generation: 1,
      details: {
        operation: 'task_owner_transfer',
        taskId: `${rootId}:task-review`,
        fromParticipantId: 'participant-present',
        toParticipantId: 'participant-future',
        ownershipRevision: 1,
      },
      createdAtMs: now + 15_000,
    }],
    cancellationSurfaces: [],
    requirementsByRootId: {
      [rootId]: {
        projectionSource: 'canonical_fixture',
        rootId,
        anchors: [{
          anchor: {
            schemaVersion: 'wisdom-weasel.requirement-anchor.v1',
            anchorId,
            rootId,
            rootSequence: 1,
            originalContentSha256: 'a'.repeat(64),
            originalByteLength: new TextEncoder().encode(originalText).byteLength,
            createdBy: 'user:preview',
            authenticity: 'original_user_bytes',
            provenance: { requestId: 'request:preview-room-task' },
            createdAtMs: now,
          },
          originalText,
          integrityStatus: 'verified',
        }],
        catalog: {
          schemaVersion: 'wisdom-weasel.requirement-catalog-revision.v1',
          catalogRevisionId,
          rootId,
          revision: 1,
          supersedesRevisionId: null,
          anchorRefs: [anchorId],
          items: [{
            itemId: `${catalogRevisionId}:item:1`,
            statement: '两项实现并行完成后再整合，并由未参与整合的伙伴独立复核',
            kind: 'explicit_user_requirement',
            state: 'active',
          }],
          acceptanceCriteria: [{
            criterionId: `${catalogRevisionId}:criterion:1`,
            itemId: `${catalogRevisionId}:item:1`,
            acceptanceCriterionFullNameZh: '并行实现、整合与独立复核验收标准',
            criterionKind: 'user_journey',
            expectedReceiptTypes: ['test'],
            statement: '依赖顺序、并行分支、整合阶段、独立复核和任务内子 Agent 均可复查',
          }],
          changeReason: '把原始请求整理成可核对的任务目录',
          provenance: { source: 'preview-room-task' },
          payloadHash: 'c'.repeat(64),
          createdBy: 'requirements-governor',
          createdAtMs: now + 1,
        },
        receiptAssessments: [],
        deliveryGate: null,
        conflicts: [],
        peerReviewRounds: [],
      },
    },
  };
}

export function previewRoomTaskSubagentRuns(
  roomId: string,
): Record<string, RoomTaskSubagentRun[]> {
  const rootId = `${roomId}:root-preview`;
  const createdAtMs = 1_754_000_000_000;
  return {
    [`${rootId}:task-interface`]: [{
      state: 'completed',
      task: '核对任务图的可访问性与依赖表达',
      templateId: 'researcher',
      ordinal: 0,
      budget: {
        maxTurns: 4,
        maxToolCalls: 8,
        maxTotalTokens: 12_000,
        maxDurationMs: 60_000,
        maxOutputChars: 4_000,
      },
      usage: {
        turnCount: 2,
        toolCount: 3,
        totalTokens: 2_400,
      },
      createdAtMs,
      startedAtMs: createdAtMs + 1_000,
      updatedAtMs: createdAtMs + 18_000,
      completedAtMs: createdAtMs + 18_000,
      resultSummary: '已确认并行分支、依赖顺序和可访问名称均清晰可读',
      error: '',
    }],
  };
}

export function previewRoomKernelReceipt(command: Record<string, unknown>): Record<string, unknown> {
  const commandKind = stringValue(command.commandKind);
  const generation = Number(command.generation) || 0;
  const commandId = stringValue(command.commandId) || 'preview-room-command';
  return {
    schemaVersion: 'wisdom-weasel.room-kernel-receipt.v1',
    receiptId: `preview:${commandId}`,
    rootId: command.rootId === null ? null : stringValue(command.rootId),
    commandId,
    receiptKind: commandKind === 'panic' ? 'panic' : 'root_cancelled',
    status: 'applied',
    generation: commandKind === 'cancel_root' ? generation + 1 : generation,
    details: { preview: true },
    createdAtMs: Date.now(),
  };
}

export function previewRoomKernelRouteManifest(): Record<string, unknown>[] {
  return [
    previewRoomKernelRoute('agent.room.kernel.snapshot', 'GET', false, ['agent.read'], []),
    previewRoomKernelRoute('agent.room.kernel.events', 'GET', true, ['agent.read'], ['lastEventId']),
    previewRoomKernelRoute('agent.room.kernel.command', 'POST', false, ['agent.write'], []),
  ];
}

function previewRoomKernelRoute(
  pathId: string,
  method: string,
  subscription: boolean,
  remoteScopes: string[],
  query: string[],
): Record<string, unknown> {
  return {
    pathId,
    method,
    remoteSafe: true,
    subscription,
    params: ['roomId'],
    query,
    remoteScopes,
  };
}

function previewParticipant(
  roomId: string,
  id: string,
  sessionId: string,
  roleId: string,
  displayName: string,
  ordinal: number,
) {
  return {
    schemaVersion: 'rag-ime.agent-participant.v1',
    id,
    roomId,
    sessionId,
    roleId,
    roleVersion: '1',
    displayName,
    collaborationRole: ordinal === 0 ? 'coordinator' : ordinal === 2 ? 'reviewer' : 'researcher',
    status: 'active',
    ordinal,
    createdAtMs: 1,
    lastSpokeAtMs: null,
  };
}

function stringValue(value: unknown): string {
  return typeof value === 'string' ? value.trim() : '';
}
