#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODEL_DIR="${RAG_IME_MLX_MODEL:-$ROOT/../models/mlx/Qwen3-0.6B-4bit}"
MLX_PYTHON="${RAG_IME_MLX_PYTHON:-$ROOT/.venv-mlx314sys/bin/python}"

if [[ ! -d "$MODEL_DIR" ]]; then
  echo "MLX model directory not found: $MODEL_DIR" >&2
  echo "Set RAG_IME_MLX_MODEL to a local MLX model directory." >&2
  exit 1
fi

if [[ ! -x "$MLX_PYTHON" ]]; then
  echo "MLX python is not executable: $MLX_PYTHON" >&2
  echo "Set RAG_IME_MLX_PYTHON to a Python that can import mlx_lm." >&2
  exit 1
fi

export RAG_IME_MLX_MODEL="$MODEL_DIR"
export RAG_IME_MLX_PYTHON="$MLX_PYTHON"
export RAG_IME_MLX_MAX_TOKENS="${RAG_IME_MLX_MAX_TOKENS:-32}"
export RAG_IME_MLX_TEMPERATURE="${RAG_IME_MLX_TEMPERATURE:-0.15}"
export RAG_IME_MLX_TOP_P="${RAG_IME_MLX_TOP_P:-0.85}"
export RAG_IME_MLX_PROMPT_CACHE="${RAG_IME_MLX_PROMPT_CACHE:-1}"

export RAG_IME_PREDICTOR_PROVIDER="${RAG_IME_PREDICTOR_PROVIDER:-mlx}"
export RAG_IME_PREDICTOR_BASE_URL="${RAG_IME_PREDICTOR_BASE_URL:-http://127.0.0.1:8767}"
export RAG_IME_PREDICTOR_MODEL="${RAG_IME_PREDICTOR_MODEL:-$MODEL_DIR}"
export RAG_IME_PREDICTOR_PROFILE="${RAG_IME_PREDICTOR_PROFILE:-instant}"
export RAG_IME_PREDICTOR_TIMEOUT_MS="${RAG_IME_PREDICTOR_TIMEOUT_MS:-2400}"
export RAG_IME_PREDICTOR_MAX_TOKENS="${RAG_IME_PREDICTOR_MAX_TOKENS:-32}"
export RAG_IME_PREDICTOR_TEMPERATURE="${RAG_IME_PREDICTOR_TEMPERATURE:-0.15}"
export RAG_IME_PREDICTOR_TOP_P="${RAG_IME_PREDICTOR_TOP_P:-0.85}"
export RAG_IME_PREDICTOR_FAILURE_COOLDOWN_MS="${RAG_IME_PREDICTOR_FAILURE_COOLDOWN_MS:-0}"

export RAG_IME_ENABLE_LOCAL_VECTOR="${RAG_IME_ENABLE_LOCAL_VECTOR:-1}"
export RAG_IME_EMBEDDING_PROVIDER="${RAG_IME_EMBEDDING_PROVIDER:-local-hash}"
export RAG_IME_EMBEDDING_DIMENSIONS="${RAG_IME_EMBEDDING_DIMENSIONS:-96}"
export RAG_IME_VECTOR_CANDIDATES="${RAG_IME_VECTOR_CANDIDATES:-80}"
export RAG_IME_VECTOR_WEIGHT="${RAG_IME_VECTOR_WEIGHT:-1.4}"
export RAG_IME_VECTOR_AUTO_REBUILD_LIMIT="${RAG_IME_VECTOR_AUTO_REBUILD_LIMIT:-5000}"

export RAG_IME_SQUIRREL_LATENCY_BUDGET_MS="${RAG_IME_SQUIRREL_LATENCY_BUDGET_MS:-3200}"
export RAG_IME_SQUIRREL_TIMEOUT_MS="${RAG_IME_SQUIRREL_TIMEOUT_MS:-9000}"

"$ROOT/scripts/install_mlx_predictor_launch_agent.sh"
"$ROOT/scripts/install_sidecar_launch_agent.sh"
"$ROOT/scripts/wait_squirrel_typing_ready.sh"
